// Domain Pack definitions — each rewrites the app's entire sensory environment

export const VOID_DEFAULT_TOKENS = {
  background: '#0a0a0f',
  surface: '#111118',
  surfaceElevated: '#1a1a24',
  border: '#2a2a3a',
  borderFocus: '#4a4a7a',
  accent: '#5a5aaa',
  accentBright: '#7a7acf',
  text: '#c0b8d0',
  textMuted: '#6a6a8a',
  kiBar: '#4a4a8a',
  kiBarFill: '#7070cf',
  shadow: '#000000',
};

export const DOMAIN_CONFIGS = {
  void_default: {
    packKey: 'void_default',
    name: 'The Void',
    description: 'Absolute darkness. The default domain. Everything else is decoration.',
    tokens: VOID_DEFAULT_TOKENS,
    particleSpec: null,
    audio: null,
    tapEffect: null,
    kiBarMaterial: 'liquid_void',
    price: null, // free default
  },

  frozen_wastes: {
    packKey: 'frozen_wastes',
    name: 'Frozen Wastes',
    description: 'Arctic blue. Frost geometry. The practitioner whose will is absolute zero.',
    tokens: {
      background: '#060c14',
      surface: '#0a1420',
      surfaceElevated: '#10202e',
      border: '#1a3050',
      borderFocus: '#3a7090',
      accent: '#4a9abf',
      accentBright: '#6abfdf',
      text: '#c0dff0',
      textMuted: '#6090a0',
      kiBar: '#1a4060',
      kiBarFill: '#4ab0d0',
      shadow: '#001020',
    },
    particleSpec: {
      type: 'ice_shard',
      count: 8,
      velocityRange: [120, 240],
      sizeRange: [4, 12],
      colorRange: ['#80c0e0', '#a0d8f0', '#c0ecff'],
      decayMs: 600,
    },
    audio: 'frozen_wastes_ambient',
    tapEffect: 'ice_shatter',
    kiBarMaterial: 'glacial_crystal',
    sessionSfx: {
      setComplete: 'ice_crack',
      logSuccess: 'deep_resonance',
    },
    price: 9.99,
  },

  ember_court: {
    packKey: 'ember_court',
    name: 'Ember Court',
    description: 'Deep orange. Heat shimmer. The domain of those who train through the burn.',
    tokens: {
      background: '#120800',
      surface: '#1e1000',
      surfaceElevated: '#2a1800',
      border: '#502010',
      borderFocus: '#904030',
      accent: '#c06030',
      accentBright: '#e08050',
      text: '#f0d0a0',
      textMuted: '#906040',
      kiBar: '#502010',
      kiBarFill: '#d07030',
      shadow: '#0a0400',
    },
    particleSpec: {
      type: 'ember',
      count: 12,
      velocityRange: [80, 200],
      sizeRange: [3, 8],
      colorRange: ['#ff6020', '#ff8040', '#ffa060'],
      decayMs: 800,
    },
    audio: 'ember_court_ambient',
    tapEffect: 'ember_burst',
    kiBarMaterial: 'molten_core',
    sessionSfx: {
      setComplete: 'ember_roar',
      logSuccess: 'metal_strike',
    },
    price: 9.99,
  },

  abyssal_rift: {
    packKey: 'abyssal_rift',
    name: 'Abyssal Rift',
    description: 'Void purple. Spatial tears. The domain where reality concedes to will.',
    tokens: {
      background: '#080010',
      surface: '#100020',
      surfaceElevated: '#180030',
      border: '#300060',
      borderFocus: '#6000a0',
      accent: '#8020c0',
      accentBright: '#a040e0',
      text: '#d0a0f0',
      textMuted: '#7040a0',
      kiBar: '#300060',
      kiBarFill: '#9030d0',
      shadow: '#04000a',
    },
    particleSpec: {
      type: 'rift_tear',
      count: 5,
      velocityRange: [60, 160],
      sizeRange: [8, 24],
      colorRange: ['#6000a0', '#8020c0', '#a040e0'],
      decayMs: 1000,
    },
    audio: 'abyssal_rift_ambient',
    tapEffect: 'dimensional_fracture',
    kiBarMaterial: 'liquid_void',
    sessionSfx: {
      setComplete: 'void_hum',
      logSuccess: 'dimensional_shift',
    },
    price: 12.99,
  },

  jade_sovereign: {
    packKey: 'jade_sovereign',
    name: 'Jade Sovereign',
    description: 'Forest green. Ancient stone. The domain of the practitioner who has become nature itself.',
    tokens: {
      background: '#020c06',
      surface: '#051408',
      surfaceElevated: '#0a1e0e',
      border: '#1a4020',
      borderFocus: '#306040',
      accent: '#408050',
      accentBright: '#60a870',
      text: '#a0d0a8',
      textMuted: '#406048',
      kiBar: '#1a4020',
      kiBarFill: '#50a060',
      shadow: '#010804',
    },
    particleSpec: {
      type: 'leaf',
      count: 10,
      velocityRange: [40, 120],
      sizeRange: [6, 16],
      colorRange: ['#408050', '#60a870', '#80c090'],
      decayMs: 1200,
    },
    audio: 'jade_sovereign_ambient',
    tapEffect: 'moss_mist',
    kiBarMaterial: 'jade_plate',
    sessionSfx: {
      setComplete: 'temple_bell',
      logSuccess: 'wind_through_stone',
    },
    price: 9.99,
  },

  storm_mandate: {
    packKey: 'storm_mandate',
    name: 'Storm Mandate',
    description: 'Electric white. Thunder cracks. The domain of pure kinetic dominance.',
    tokens: {
      background: '#060810',
      surface: '#0c1020',
      surfaceElevated: '#141830',
      border: '#202840',
      borderFocus: '#4060a0',
      accent: '#6080d0',
      accentBright: '#90b0ff',
      text: '#d0e0ff',
      textMuted: '#6070a0',
      kiBar: '#202840',
      kiBarFill: '#7090e0',
      shadow: '#020408',
    },
    particleSpec: {
      type: 'lightning',
      count: 4,
      velocityRange: [200, 400],
      sizeRange: [2, 6],
      colorRange: ['#c0d8ff', '#e0ecff', '#ffffff'],
      decayMs: 200,
    },
    audio: 'storm_mandate_ambient',
    tapEffect: 'lightning_fork',
    kiBarMaterial: 'charged_plasma',
    sessionSfx: {
      setComplete: 'thunder_crack',
      logSuccess: 'static_discharge',
    },
    price: 9.99,
  },
};

export function getDomainConfig(packKey) {
  return DOMAIN_CONFIGS[packKey] ?? DOMAIN_CONFIGS.void_default;
}
